### ISSUE TITLE
Chess: Move A5 to A4

### ISSUE THREAD

**Issue by denilsonpy** [import-brain/import-brain#14]
Please do not change the title. Just click "Submit new issue". You don't need to do anything else :D

**Comment by denilsonpy** [comment]
Wow that's amazing!!:D

**Comment by import-brain** [comment]
> Wow that's amazing!!:D

Yeah mate! There's a link to make your own at the bottom of the chess thing :)

**Comment by denilsonpy** [comment]
Thank youuu:D

**Comment by import-brain** [comment]
> Thank youuu:D

:)
